# Site
name: "Abhishek's Blog"
description: "A place where I write, sometimes!"
meta_description: "abhishek sharma, abhishek manoj sharma, computer science, software developer, data science, etl, warehousing, diet, cricket"
logo: 'assets/images/abhishek-sharma-logo.png'
favicon: 'assets/images/abhishek-sharma-logo.png'
baseurl: /blog
home: abhishekmsharma.com
google_analytics: 'UA-46278016-1'
#disqus: 'abhishekmsharma-1'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

# Authors
authors:
  abhishek:
    name: Abhishek Manoj Sharma
    display_name: Abhishek
    gravatar: ca33c510960406d3b0edda34788dc55d
    email: 
    web: 
    twitter: https://twitter.com/abhishekmsharma
    description: "Graduate Computer Science student. Tech enthusiast. Loves cricket and table-tennis."

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown
highlighter: rouge
